name: numeric_utils
description: Provides extensions and utility functions for working with numeric types in Dart, including Rational and BigInt.
version: 0.4.3
repository: https://github.com/fredspizza/numeric_utils

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  rational: ^2.0.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0